final List<Map<String, dynamic>> foods = [
    {
      "name": "Thon au Naturel Ricamar",
      "brand": "Ricamar",
      "category": "Canned Fish",
      "origin": "Algeria",
      "caloriesPer100g": 116.0,
      "proteinsPer100g": 26.0,
      "carbsPer100g": 0.0,
      "fatsPer100g": 1.0,
      "healthLevel": "good",
      "image": "assets/images/foods/thon_naturel_ricamar.png"
    },
    {
      "name": "Thon à la Tomate Ricamar",
      "brand": "Ricamar",
      "category": "Canned Fish",
      "origin": "Algeria",
      "caloriesPer100g": 145.0,
      "proteinsPer100g": 20.0,
      "carbsPer100g": 4.0,
      "fatsPer100g": 5.5,
      "healthLevel": "medium",
      "image": "assets/images/foods/thon_tomate_ricamar.png"
    },
    {
      "name": "Thon à l’Huile Végétale Ricamar ",
      "brand": "Ricamar",
      "category": "Canned Fish",
      "origin": "Algeria",
      "caloriesPer100g": 198.0,
      "proteinsPer100g": 24.0,
      "carbsPer100g": 0.0,
      "fatsPer100g": 11.0,
      "healthLevel": "medium",
      "image": "assets/images/foods/thon_huile_ricamar.png"
    },
    {
      "name": "Couscous Amor Benamor Seffa",
      "brand": "Amor Benamor",
      "category": "Grains",
      "origin": "Algeria",
      "caloriesPer100g": 360.0,
      "proteinsPer100g": 12.0,
      "carbsPer100g": 72.0,
      "fatsPer100g": 1.5,
      "healthLevel": "good",
      "image": "assets/images/foods/couscous_amor_benamor_seffa.png"
    },
    {
      "name": "Makaroun Amor Benamor Coquillettes",
      "brand": "Amor Benamor",
      "category": "Pasta",
      "origin": "Algeria",
      "caloriesPer100g": 371.0,
      "proteinsPer100g": 13.0,
      "carbsPer100g": 74.0,
      "fatsPer100g": 1.5,
      "healthLevel": "medium",
      "image": "assets/images/foods/makaroun_amor_benamor_coquillettes.png"
    },
    {
      "name": "Mhamsa Amor Benamor Plombs",
      "brand": "Amor Benamor",
      "category": "Pasta",
      "origin": "Algeria",
      "caloriesPer100g": 368.0,
      "proteinsPer100g": 12.5,
      "carbsPer100g": 73.0,
      "fatsPer100g": 1.4,
      "healthLevel": "medium",
      "image": "assets/images/foods/mhamsa_amor_benamor_plombs.png"
    },
    {
      "name": "Makaroun Spaghetti Amor Benamor Languine",
      "brand": "Amor Benamor",
      "category": "Pasta",
      "origin": "Algeria",
      "caloriesPer100g": 370.0,
      "proteinsPer100g": 13.0,
      "carbsPer100g": 74.0,
      "fatsPer100g": 1.5,
      "healthLevel": "medium",
      "image": "assets/images/foods/makaroun_spaghetti_amor_benamor_languine.png"
    },
    {
      "name": "Dwida Amor Benamor Cheveux d’Anges",
      "brand": "Amor Benamor",
      "category": "Pasta",
      "origin": "Algeria",
      "caloriesPer100g": 369.0,
      "proteinsPer100g": 12.0,
      "carbsPer100g": 74.0,
      "fatsPer100g": 1.3,
      "healthLevel": "medium",
      "image": "assets/images/foods/dwida_amor_benamor_cheveux_danges.png"
    }
  // =========================
  // FRUITS
  // =========================
  ,{
    "name": "Banana",
    "brand": "Local",
    "category": "Fruits",
    "origin": "Local / Market",
    "caloriesPer100g": 89.0,
    "proteinsPer100g": 1.1,
    "carbsPer100g": 22.8,
    "fatsPer100g": 0.3,
    "healthLevel": "good",
    "image": "assets/images/foods/banana.png",
  },
  {
    "name": "Apple",
    "brand": "Local",
    "category": "Fruits",
    "origin": "Local / Market",
    "caloriesPer100g": 52.0,
    "proteinsPer100g": 0.3,
    "carbsPer100g": 14.0,
    "fatsPer100g": 0.2,
    "healthLevel": "good",
    "image": "assets/images/foods/apple.png",
  },
  {
    "name": "Orange",
    "brand": "Local",
    "category": "Fruits",
    "origin": "Local / Market",
    "caloriesPer100g": 47.0,
    "proteinsPer100g": 0.9,
    "carbsPer100g": 12.0,
    "fatsPer100g": 0.1,
    "healthLevel": "good",
    "image": "assets/images/foods/orange.png",
  },
  {
    "name": "Mandarin",
    "brand": "Local",
    "category": "Fruits",
    "origin": "Local / Market",
    "caloriesPer100g": 53.0,
    "proteinsPer100g": 0.8,
    "carbsPer100g": 13.3,
    "fatsPer100g": 0.3,
    "healthLevel": "good",
    "image": "assets/images/foods/mandarine.png",
  },
  {
    "name": "Dates (Deglet Nour)",
    "brand": "Local",
    "category": "Fruits",
    "origin": "Algerian Local",
    "caloriesPer100g": 282.0,
    "proteinsPer100g": 2.5,
    "carbsPer100g": 75.0,
    "fatsPer100g": 0.4,
    "healthLevel": "good",
    "image": "assets/images/foods/dates.png",
  },
  {
    "name": "Strawberry",
    "brand": "Local",
    "category": "Fruits",
    "origin": "Local / Market",
    "caloriesPer100g": 32.0,
    "proteinsPer100g": 0.7,
    "carbsPer100g": 7.7,
    "fatsPer100g": 0.3,
    "healthLevel": "good",
    "image": "assets/images/foods/strawberry.png",
  },
  {
    "name": "Watermelon",
    "brand": "Local",
    "category": "Fruits",
    "origin": "Local / Market",
    "caloriesPer100g": 30.0,
    "proteinsPer100g": 0.6,
    "carbsPer100g": 7.6,
    "fatsPer100g": 0.2,
    "healthLevel": "good",
    "image": "assets/images/foods/watermelon.png",
  },
  {
    "name": "Melon",
    "brand": "Local",
    "category": "Fruits",
    "origin": "Local / Market",
    "caloriesPer100g": 34.0,
    "proteinsPer100g": 0.8,
    "carbsPer100g": 8.2,
    "fatsPer100g": 0.2,
    "healthLevel": "good",
    "image": "assets/images/foods/melon.png",
  },
  {
    "name": "Grapes",
    "brand": "Local",
    "category": "Fruits",
    "origin": "Local / Market",
    "caloriesPer100g": 69.0,
    "proteinsPer100g": 0.7,
    "carbsPer100g": 18.1,
    "fatsPer100g": 0.2,
    "healthLevel": "good",
    "image": "assets/images/foods/grapes.png",
  },
  {
    "name": "Pear",
    "brand": "Local",
    "category": "Fruits",
    "origin": "Local / Market",
    "caloriesPer100g": 57.0,
    "proteinsPer100g": 0.4,
    "carbsPer100g": 15.0,
    "fatsPer100g": 0.1,
    "healthLevel": "good",
    "image": "assets/images/foods/pear.png",
  },
  {
    "name": "Peach",
    "brand": "Local",
    "category": "Fruits",
    "origin": "Local / Market",
    "caloriesPer100g": 39.0,
    "proteinsPer100g": 0.9,
    "carbsPer100g": 9.5,
    "fatsPer100g": 0.3,
    "healthLevel": "good",
    "image": "assets/images/foods/peach.png",
  },
  {
    "name": "Apricot",
    "brand": "Local",
    "category": "Fruits",
    "origin": "Local / Market",
    "caloriesPer100g": 48.0,
    "proteinsPer100g": 1.4,
    "carbsPer100g": 11.0,
    "fatsPer100g": 0.4,
    "healthLevel": "good",
    "image": "assets/images/foods/apricot.png",
  },

  // =========================
  // VEGETABLES
  // =========================
  {
    "name": "Tomato",
    "brand": "Local",
    "category": "Vegetables",
    "origin": "Local / Market",
    "caloriesPer100g": 18.0,
    "proteinsPer100g": 0.9,
    "carbsPer100g": 3.9,
    "fatsPer100g": 0.2,
    "healthLevel": "good",
    "image": "assets/images/foods/tomato.png",
  },
  {
    "name": "Carrot",
    "brand": "Local",
    "category": "Vegetables",
    "origin": "Local / Market",
    "caloriesPer100g": 41.0,
    "proteinsPer100g": 0.9,
    "carbsPer100g": 9.6,
    "fatsPer100g": 0.2,
    "healthLevel": "good",
    "image": "assets/images/foods/carrot.png",
  },
  {
    "name": "Potato",
    "brand": "Local",
    "category": "Vegetables",
    "origin": "Local / Market",
    "caloriesPer100g": 77.0,
    "proteinsPer100g": 2.0,
    "carbsPer100g": 17.0,
    "fatsPer100g": 0.1,
    "healthLevel": "good",
    "image": "assets/images/foods/potato.png",
  },
  {
    "name": "Zucchini",
    "brand": "Local",
    "category": "Vegetables",
    "origin": "Local / Market",
    "caloriesPer100g": 17.0,
    "proteinsPer100g": 1.2,
    "carbsPer100g": 3.1,
    "fatsPer100g": 0.3,
    "healthLevel": "good",
    "image": "assets/images/foods/zucchini.png",
  },
  {
    "name": "Onion",
    "brand": "Local",
    "category": "Vegetables",
    "origin": "Local / Market",
    "caloriesPer100g": 40.0,
    "proteinsPer100g": 1.1,
    "carbsPer100g": 9.3,
    "fatsPer100g": 0.1,
    "healthLevel": "good",
    "image": "assets/images/foods/onion.png",
  },
  {
    "name": "Bell Pepper",
    "brand": "Local",
    "category": "Vegetables",
    "origin": "Local / Market",
    "caloriesPer100g": 31.0,
    "proteinsPer100g": 1.0,
    "carbsPer100g": 6.0,
    "fatsPer100g": 0.3,
    "healthLevel": "good",
    "image": "assets/images/foods/pepper.png",
  },
  {
    "name": "Lettuce",
    "brand": "Local",
    "category": "Vegetables",
    "origin": "Local / Market",
    "caloriesPer100g": 15.0,
    "proteinsPer100g": 1.4,
    "carbsPer100g": 2.9,
    "fatsPer100g": 0.2,
    "healthLevel": "good",
    "image": "assets/images/foods/lettuce.png",
  },
  {
    "name": "Cucumber",
    "brand": "Local",
    "category": "Vegetables",
    "origin": "Local / Market",
    "caloriesPer100g": 15.0,
    "proteinsPer100g": 0.7,
    "carbsPer100g": 3.6,
    "fatsPer100g": 0.1,
    "healthLevel": "good",
    "image": "assets/images/foods/cucumber.png",
  },
  {
    "name": "Eggplant",
    "brand": "Local",
    "category": "Vegetables",
    "origin": "Local / Market",
    "caloriesPer100g": 25.0,
    "proteinsPer100g": 1.0,
    "carbsPer100g": 6.0,
    "fatsPer100g": 0.2,
    "healthLevel": "good",
    "image": "assets/images/foods/eggplant.png",
  },
  {
    "name": "Green Beans",
    "brand": "Local",
    "category": "Vegetables",
    "origin": "Local / Market",
    "caloriesPer100g": 31.0,
    "proteinsPer100g": 1.8,
    "carbsPer100g": 7.0,
    "fatsPer100g": 0.1,
    "healthLevel": "good",
    "image": "assets/images/foods/green_beans.png",
  },

  // ANIMAL PROTEIN
  {
    "name": "Chicken",
    "brand": "Local",
    "category": "Animal Protein",
    "origin": "Local / Market",
    "caloriesPer100g": 165.0,
    "proteinsPer100g": 31.0,
    "carbsPer100g": 0.0,
    "fatsPer100g": 3.6,
    "healthLevel": "good",
    "image": "assets/images/foods/chicken.png",
  },
  {
    "name": "Red Meat",
    "brand": "Local",
    "category": "Animal Protein",
    "origin": "Local / Market",
    "caloriesPer100g": 250.0,
    "proteinsPer100g": 26.0,
    "carbsPer100g": 0.0,
    "fatsPer100g": 15.0,
    "healthLevel": "medium",
    "image": "assets/images/foods/red_meat.png",
  },
  {
    "name": "Fish",
    "brand": "Local",
    "category": "Animal Protein",
    "origin": "Local / Market",
    "caloriesPer100g": 206.0,
    "proteinsPer100g": 22.0,
    "carbsPer100g": 0.0,
    "fatsPer100g": 12.0,
    "healthLevel": "good",
    "image": "assets/images/foods/fish.png",
  },
  {
    "name": "Eggs",
    "brand": "Local",
    "category": "Animal Protein",
    "origin": "Local / Market",
    "caloriesPer100g": 155.0,
    "proteinsPer100g": 13.0,
    "carbsPer100g": 1.1,
    "fatsPer100g": 11.0,
    "healthLevel": "good",
    "image": "assets/images/foods/eggs.png",
  },

  // GENERAL DAIRY PRODUCTS
  {
    "name": "Milk",
    "brand": "Candia",
    "category": "Dairy Products",
    "origin": "Algerian Store",
    "caloriesPer100g": 61.0,
    "proteinsPer100g": 3.2,
    "carbsPer100g": 4.8,
    "fatsPer100g": 3.3,
    "healthLevel": "good",
    "image": "assets/images/foods/candia_milk.png",
  },
  {
    "name": "Yogurt",
    "brand": "Danone",
    "category": "Dairy Products",
    "origin": "Algerian Store",
    "caloriesPer100g": 59.0,
    "proteinsPer100g": 10.0,
    "carbsPer100g": 3.6,
    "fatsPer100g": 0.4,
    "healthLevel": "good",
    "image": "assets/images/foods/danone_yogurt.png",
  },
  {
    "name": "Lben",
    "brand": "Local",
    "category": "Dairy Products",
    "origin": "Local / Market",
    "caloriesPer100g": 40.0,
    "proteinsPer100g": 3.3,
    "carbsPer100g": 4.8,
    "fatsPer100g": 1.0,
    "healthLevel": "good",
    "image": "assets/images/foods/lben.png",
  },
  {
    "name": "Raib",
    "brand": "Local",
    "category": "Dairy Products",
    "origin": "Local / Market",
    "caloriesPer100g": 63.0,
    "proteinsPer100g": 3.5,
    "carbsPer100g": 4.7,
    "fatsPer100g": 3.2,
    "healthLevel": "medium",
    "image": "assets/images/foods/raib.png",
  },
  {
    "name": "Cheese",
    "brand": "Local",
    "category": "Dairy Products",
    "origin": "Store Product",
    "caloriesPer100g": 402.0,
    "proteinsPer100g": 25.0,
    "carbsPer100g": 1.3,
    "fatsPer100g": 33.0,
    "healthLevel": "medium",
    "image": "assets/images/foods/cheese.png",
  },

  // SOUMMAM PRODUCTS
  {
    "name": "Yogurt",
    "brand": "Soummam",
    "category": "Dairy Products",
    "origin": "Algerian Store",
    "caloriesPer100g": 48.2,
    "proteinsPer100g": 3.5,
    "carbsPer100g": 4.3,
    "fatsPer100g": 1.9,
    "healthLevel": "good",
    "image": "assets/images/foods/yogurt_soummam.png",
  },
  {
    "name": "Yogurt Light",
    "brand": "Soummam",
    "category": "Dairy Products",
    "origin": "Algerian Store",
    "caloriesPer100g": 44.8,
    "proteinsPer100g": 3.6,
    "carbsPer100g": 4.3,
    "fatsPer100g": 1.4,
    "healthLevel": "good",
    "image": "assets/images/foods/yogurt_light_soummam.png",
  },
  {
    "name": "J'nina Strawberry Drink",
    "brand": "Soummam",
    "category": "Dairy Drinks",
    "origin": "Algerian Store",
    "caloriesPer100g": 75.1,
    "proteinsPer100g": 1.6,
    "carbsPer100g": 13.6,
    "fatsPer100g": 1.6,
    "healthLevel": "medium",
    "image": "assets/images/foods/soummam_jnina_strawberry.png",
  },
  {
    "name": "L'Ben",
    "brand": "Soummam",
    "category": "Dairy Products",
    "origin": "Algerian Store",
    "caloriesPer100g": 40.9,
    "proteinsPer100g": 2.7,
    "carbsPer100g": 3.3,
    "fatsPer100g": 1.9,
    "healthLevel": "good",
    "image": "assets/images/foods/lben_soummam.png",
  },
  {
    "name": "Raib with Bifidus",
    "brand": "Soummam",
    "category": "Dairy Products",
    "origin": "Algerian Store",
    "caloriesPer100g": 80.0,
    "proteinsPer100g": 3.2,
    "carbsPer100g": 11.5,
    "fatsPer100g": 2.3,
    "healthLevel": "medium",
    "image": "assets/images/foods/raib_bifidus_soummam.png",
  },
  {
    "name": "Whole Milk",
    "brand": "Soummam",
    "category": "Milk",
    "origin": "Algerian Store",
    "caloriesPer100g": 64.0,
    "proteinsPer100g": 3.2,
    "carbsPer100g": 4.8,
    "fatsPer100g": 3.6,
    "healthLevel": "good",
    "image": "assets/images/foods/soummam_whole_milk.png",
  },
  {
    "name": "Semi-Skimmed Milk",
    "brand": "Soummam",
    "category": "Milk",
    "origin": "Algerian Store",
    "caloriesPer100g": 50.0,
    "proteinsPer100g": 3.2,
    "carbsPer100g": 4.8,
    "fatsPer100g": 1.5,
    "healthLevel": "good",
    "image": "assets/images/foods/soummam_semi_skimmed_milk.png",
  },
  {
    "name": "Vitamilk",
    "brand": "Soummam",
    "category": "Milk",
    "origin": "Algerian Store",
    "caloriesPer100g": 60.0,
    "proteinsPer100g": 3.0,
    "carbsPer100g": 5.0,
    "fatsPer100g": 3.0,
    "healthLevel": "good",
    "image": "assets/images/foods/soummam_vitamilk.png",
  },
  {
    "name": "Slim Milk",
    "brand": "Soummam",
    "category": "Milk",
    "origin": "Algerian Store",
    "caloriesPer100g": 42.0,
    "proteinsPer100g": 3.1,
    "carbsPer100g": 4.8,
    "fatsPer100g": 0.8,
    "healthLevel": "good",
    "image": "assets/images/foods/soummam_slim_milk.png",
  },
  {
    "name": "Fresh Cheese",
    "brand": "Soummam",
    "category": "Cheese",
    "origin": "Algerian Store",
    "caloriesPer100g": 98.0,
    "proteinsPer100g": 7.0,
    "carbsPer100g": 4.0,
    "fatsPer100g": 5.5,
    "healthLevel": "good",
    "image": "assets/images/foods/soummam_fresh_cheese.png",
  },
  {
    "name": "Tartifrais",
    "brand": "Soummam",
    "category": "Cheese",
    "origin": "Algerian Store",
    "caloriesPer100g": 250.0,
    "proteinsPer100g": 8.0,
    "carbsPer100g": 5.0,
    "fatsPer100g": 20.0,
    "healthLevel": "medium",
    "image": "assets/images/foods/soummam_tartifrais.png",
  },
  {
    "name": "Delices Spread Cheese",
    "brand": "Soummam",
    "category": "Cheese",
    "origin": "Algerian Store",
    "caloriesPer100g": 290.0,
    "proteinsPer100g": 10.0,
    "carbsPer100g": 6.0,
    "fatsPer100g": 24.0,
    "healthLevel": "medium",
    "image": "assets/images/foods/soummam_delices.png",
  },

  // GRAINS / STARCHES
  {
    "name": "Bread Baguette",
    "brand": "Local",
    "category": "Grains and Starches",
    "origin": "Algerian Local",
    "caloriesPer100g": 265.0,
    "proteinsPer100g": 9.0,
    "carbsPer100g": 49.0,
    "fatsPer100g": 3.2,
    "healthLevel": "medium",
    "image": "assets/images/foods/khobz.png",
  },
  {
    "name": "Whole Wheat Bread",
    "brand": "Local",
    "category": "Grains and Starches",
    "origin": "Algerian Local",
    "caloriesPer100g": 247.0,
    "proteinsPer100g": 12.0,
    "carbsPer100g": 41.0,
    "fatsPer100g": 4.2,
    "healthLevel": "good",
    "image": "assets/images/foods/khobz_complet.png",
  },
  {
    "name": "Semolina Couscous",
    "brand": "Local",
    "category": "Grains and Starches",
    "origin": "Algerian Local",
    "caloriesPer100g": 376.0,
    "proteinsPer100g": 13.0,
    "carbsPer100g": 77.0,
    "fatsPer100g": 1.0,
    "healthLevel": "good",
    "image": "assets/images/foods/couscous.png",
  },
  {
    "name": "Rechta",
    "brand": "Local",
    "category": "Grains and Starches",
    "origin": "Algerian Local",
    "caloriesPer100g": 340.0,
    "proteinsPer100g": 12.0,
    "carbsPer100g": 70.0,
    "fatsPer100g": 2.0,
    "healthLevel": "medium",
    "image": "assets/images/foods/rechta.png",
  },
  {
    "name": "Rice",
    "brand": "Local",
    "category": "Grains and Starches",
    "origin": "Market / Store",
    "caloriesPer100g": 130.0,
    "proteinsPer100g": 2.7,
    "carbsPer100g": 28.0,
    "fatsPer100g": 0.3,
    "healthLevel": "good",
    "image": "assets/images/foods/rice.png",
  },
  {
    "name": "Pasta",
    "brand": "Local",
    "category": "Grains and Starches",
    "origin": "Market / Store",
    "caloriesPer100g": 131.0,
    "proteinsPer100g": 5.0,
    "carbsPer100g": 25.0,
    "fatsPer100g": 1.1,
    "healthLevel": "good",
    "image": "assets/images/foods/pasta.png",
  },
  {
    "name": "Oats",
    "brand": "Local",
    "category": "Grains and Starches",
    "origin": "Store Product",
    "caloriesPer100g": 389.0,
    "proteinsPer100g": 16.9,
    "carbsPer100g": 66.3,
    "fatsPer100g": 6.9,
    "healthLevel": "good",
    "image": "assets/images/foods/oats.png",
  },

  // SIM PRODUCTS
  {
    "name": "Semolina",
    "brand": "SIM",
    "category": "Grains and Starches",
    "origin": "Algerian Store",
    "caloriesPer100g": 360.0,
    "proteinsPer100g": 12.0,
    "carbsPer100g": 72.0,
    "fatsPer100g": 1.5,
    "healthLevel": "good",
    "image": "assets/images/foods/sim_semoule.png",
  },
  {
    "name": "Raw Couscous",
    "brand": "SIM",
    "category": "Grains and Starches",
    "origin": "Algerian Store",
    "caloriesPer100g": 376.0,
    "proteinsPer100g": 13.0,
    "carbsPer100g": 77.0,
    "fatsPer100g": 1.0,
    "healthLevel": "good",
    "image": "assets/images/foods/sim_couscous.png",
  },
  {
    "name": "Cooked Couscous",
    "brand": "SIM",
    "category": "Grains and Starches",
    "origin": "Algerian Store",
    "caloriesPer100g": 112.0,
    "proteinsPer100g": 3.8,
    "carbsPer100g": 23.2,
    "fatsPer100g": 0.2,
    "healthLevel": "good",
    "image": "assets/images/foods/sim_couscous_cuit.png",
  },

  // LEGUMES
  {
    "name": "Cooked Lentils",
    "brand": "Local",
    "category": "Legumes",
    "origin": "Local / Market",
    "caloriesPer100g": 116.0,
    "proteinsPer100g": 9.0,
    "carbsPer100g": 20.0,
    "fatsPer100g": 0.4,
    "healthLevel": "good",
    "image": "assets/images/foods/lentils.png",
  },
  {
    "name": "Cooked Chickpeas",
    "brand": "Local",
    "category": "Legumes",
    "origin": "Local / Market",
    "caloriesPer100g": 164.0,
    "proteinsPer100g": 8.9,
    "carbsPer100g": 27.0,
    "fatsPer100g": 2.6,
    "healthLevel": "good",
    "image": "assets/images/foods/chickpeas.png",
  },
  {
    "name": "Cooked White Beans",
    "brand": "Local",
    "category": "Legumes",
    "origin": "Local / Market",
    "caloriesPer100g": 140.0,
    "proteinsPer100g": 9.0,
    "carbsPer100g": 25.0,
    "fatsPer100g": 0.6,
    "healthLevel": "good",
    "image": "assets/images/foods/white_beans.png",
  },

  // ALGERIAN DISHES
  {
    "name": "Chorba",
    "brand": "Local",
    "category": "Algerian Dishes",
    "origin": "Algerian Local",
    "caloriesPer100g": 70.0,
    "proteinsPer100g": 4.0,
    "carbsPer100g": 8.0,
    "fatsPer100g": 3.0,
    "healthLevel": "good",
    "image": "assets/images/foods/chorba.png",
  },
  {
    "name": "Hmiss",
    "brand": "Local",
    "category": "Algerian Dishes",
    "origin": "Algerian Local",
    "caloriesPer100g": 90.0,
    "proteinsPer100g": 2.0,
    "carbsPer100g": 8.0,
    "fatsPer100g": 5.0,
    "healthLevel": "good",
    "image": "assets/images/foods/hmis.png",
  },
  {
    "name": "Kesra",
    "brand": "Local",
    "category": "Algerian Dishes",
    "origin": "Algerian Local",
    "caloriesPer100g": 280.0,
    "proteinsPer100g": 7.0,
    "carbsPer100g": 52.0,
    "fatsPer100g": 4.0,
    "healthLevel": "medium",
    "image": "assets/images/foods/kesra.png",
  },
  {
    "name": "Mhadjeb",
    "brand": "Local",
    "category": "Algerian Dishes",
    "origin": "Algerian Local",
    "caloriesPer100g": 250.0,
    "proteinsPer100g": 6.0,
    "carbsPer100g": 35.0,
    "fatsPer100g": 9.0,
    "healthLevel": "medium",
    "image": "assets/images/foods/mhadjeb.png",
  },
  {
    "name": "Bourek",
    "brand": "Local",
    "category": "Algerian Dishes",
    "origin": "Algerian Local",
    "caloriesPer100g": 290.0,
    "proteinsPer100g": 8.0,
    "carbsPer100g": 25.0,
    "fatsPer100g": 17.0,
    "healthLevel": "bad",
    "image": "assets/images/foods/bourek.png",
  },
  // STORE PRODUCTS
  {
    "name": "Orange Juice",
    "brand": "Rouiba",
    "category": "Store Products",
    "origin": "Algerian Store",
    "caloriesPer100g": 44.0,
    "proteinsPer100g": 0.5,
    "carbsPer100g": 10.0,
    "fatsPer100g": 0.1,
    "healthLevel": "medium",
    "image": "assets/images/foods/rouiba_orange.png",
  },
  {
    "name": "Bissousse",
    "brand": "Bimo",
    "category": "Store Products",
    "origin": "Store Product",
    "caloriesPer100g": 476.0,
    "proteinsPer100g": 7.6,
    "carbsPer100g": 69.0,
    "fatsPer100g": 19.0,
    "healthLevel": "bad",
    "image": "assets/images/foods/bimo_bissousse.png",
  },
  {
    "name": "Jam",
    "brand": "Local",
    "category": "Store Products",
    "origin": "Store Product",
    "caloriesPer100g": 250.0,
    "proteinsPer100g": 0.3,
    "carbsPer100g": 65.0,
    "fatsPer100g": 0.1,
    "healthLevel": "bad",
    "image": "assets/images/foods/jam.png",
  },
  {
    "name": "Chocolate Spread",
    "brand": "Local",
    "category": "Store Products",
    "origin": "Store Product",
    "caloriesPer100g": 530.0,
    "proteinsPer100g": 6.0,
    "carbsPer100g": 57.0,
    "fatsPer100g": 31.0,
    "healthLevel": "bad",
    "image": "assets/images/foods/chocolate_spread.png",
  },

  // NUTS
  {
    "name": "Almonds",
    "brand": "Local",
    "category": "Nuts",
    "origin": "Local / Market",
    "caloriesPer100g": 579.0,
    "proteinsPer100g": 21.0,
    "carbsPer100g": 22.0,
    "fatsPer100g": 50.0,
    "healthLevel": "good",
    "image": "assets/images/foods/almonds.png",
  },
  {
    "name": "Walnuts",
    "brand": "Local",
    "category": "Nuts",
    "origin": "Local / Market",
    "caloriesPer100g": 654.0,
    "proteinsPer100g": 15.0,
    "carbsPer100g": 14.0,
    "fatsPer100g": 65.0,
    "healthLevel": "good",
    "image": "assets/images/foods/walnuts.png",
  },
  {
    "name": "Peanuts",
    "brand": "Local",
    "category": "Nuts",
    "origin": "Local / Market",
    "caloriesPer100g": 567.0,
    "proteinsPer100g": 26.0,
    "carbsPer100g": 16.0,
    "fatsPer100g": 49.0,
    "healthLevel": "medium",
    "image": "assets/images/foods/peanuts.png",
  },
];


